apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.0
        ports:
        - containerPort: 80
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "myapp"
        effect: "NoSchedule"

#here we deployed nginix with tolerations of NoSchedule. Inorder to check create a taint on any node 
#by deploying this we can see the load distribution on taint node also
#to crete deploymetn use

#kubectl apply -f dep-toleration.yml
#kubectl get deployment 
