apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: demo2
  name: demo2
spec:
  containers:
  - image: nginx
    name: demo2
    resources: {}
  nodeSelector:
    kalki: prabhas
  dnsPolicy: ClusterFirst
  restartPolicy: Always