apiVersion: v1
kind: Service
metadata:
  name: harshasvc
spec:
  type : NodePort
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30005
      targetPort: 80

#to create or configure this service file
#kubectl apply -f svc.yml
#to get svc name use
#kubectl get svc
#In this service we added deployment which has label app=wordpress