FROM ubuntu
RUN sudo apt install nginx -y
RUN sudo apt install curl wget net-tools
RUN sudo rm -rf /etc/nginx/nginx.conf
COPY ./nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["echo", "Hello, Docker!"]

 

